Departmentcontactemails
wvulibraries/library_directory pull request #48
Opened 2021-02-15 16:23 UTC by trmccormick

# Department Contact Emails
Created a new Model called emails that is setup as a polymorphic association to the department model. So we have the ability to add email address in the same fashion that we add phone numbers to the department contact list.

Created or Modified the following files
-  /app/assets/stylesheets/frontend/_department.scss 
-  /app/assets/stylesheets/frontend/_display-list.scss
-  /app/controllers/admin/departments_controller.rb
-  /app/models/department.rb
-  /app/models/email.rb
-  /app/views/admin/_email.html.erb
-  /app/views/admin/departments/_form.html.erb
-  /app/views/admin/departments/index.html.erb
-  /app/views/department/details.html.erb
-  /app/views/department/list.html.erb
-  /db/migrate/20210212165404_create_emails.rb
-  /db/schema.rb
-  /spec/factories/departments.rb
-  /spec/factories/emails.rb
-  /spec/features/departments_spec.rb
-  /spec/models/email_spec.rb

## Description
Generated new migration / model called email. Model is setup as a polymorphic association to the department model. Updated views and generated rspec tests.

## Related Issue
https://github.com/wvulibraries/library_directory/issues/45

## Motivation and Context
Requested feature addition.

## How Has This Been Tested?
Created Rspec tests and also did manual testing when changes were completed.

## Screenshots (if appropriate):

2021-02-15 18:11 UTC, ddavisgraphics commented on app/views/admin/_email.html.erb
> +    <%= form.text_field :address, placeholder: 'somebody@mail.wvu.edu' %>
person@mail.wvu.edu

2021-02-15 18:12 UTC, ddavisgraphics commented on app/views/admin/departments/index.html.erb
> +        <% if dept.emails.length %>
present?

2021-02-15 18:16 UTC, ddavisgraphics commented on app/views/department/details.html.erb
> +              <a href="mailto:<%= email.address %>">
title="<%= email.address %>" 
OR 

title="<%= @department.name %> email address <%= @email.address %>"

2021-02-15 18:19 UTC, ddavisgraphics requested changes
Changes required.

2021-02-22 16:40 UTC, trmccormick commented on app/views/admin/_email.html.erb
> +    <%= form.text_field :address, placeholder: 'somebody@mail.wvu.edu' %>
made adjustements

2021-02-22 16:40 UTC, trmccormick commented on app/views/admin/departments/index.html.erb
> +        <% if dept.emails.length %>
made changes

2021-02-22 16:40 UTC, merged